-- DATABASE CONSOLE

-- ALL DELETE

-- DELETE FROM Userinfos;
-- DELETE FROM Resumes;
-- DELETE FROM UserHistories;
-- DELETE FROM Users;

-- ALTER TABLE Users AUTO_INCREMENT=1;
-- ALTER TABLE Userinfos AUTO_INCREMENT=1;
-- ALTER TABLE UserHistories AUTO_INCREMENT=1;
-- ALTER TABLE Resumes AUTO_INCREMENT=1;



-- SELECT * FROM Users;
-- SELECT * FROM Userinfos;